### ISSUE TITLE
I used by mistake the ETH address to send ERC20 tokens

### ISSUE THREAD

**Issue by arko36** [almindor/etherwall#122]
Hi, by mistake i used the ETH address to send some tokens (LINK) I can see the transaction in the etherscan but the wallet shows zero obviously. How can I recover these tokens ?!
Thanks in advance
Ariel

**Comment by almindor** [comment]
Hey,

I need more details to help. Do you own the destination address/account?

**Comment by arko36** [comment]
Yes, the destination is a etherwall address, I sent some LINK token to that
address which is ETH address in etherwall wallet. I saw there is a way to
brin the token via contract to etherwall to store them (ERC20) but I don
know how .

Thanks in advance for the help.

Ariel

**Comment by almindor** [comment]
Ah that's an easy fix. You need to go to the contracts tab and "add existing contract" then put `0x514910771AF9Ca656af840dff83E8264EcF986CA` in the address field. The rest should auto-fill and then just add contract.

*NOTE* you should double check that the LINK contract I give you here is the LINK contract you've used (e.g. that it belongs to your token etc.)

After that you will get the token in the token selection combobox at the top. Select link and check your balance and total. You can then send the token out as a transaction by also selecting it in the new transaction dialog for the right account.

NOTE: there was a UI bug preventing showing the account balances in tokens in v3.0.0 #123 it has been since fixed and v3.0.1 ia available for download now. You can also see your totals even in v3.0.0 and in the transaction dialog. This bug does not affect sending functionality it's purely cosmetic.

**Comment by arko36** [comment]
It worked !!! Thanks !
