### ISSUE TITLE
Daily Requests?

### ISSUE THREAD

**Issue by Woor** [almindor/etherwall#130]
So I keep getting an error at startup:

"daily request count exceeded, request rate limited".
Can't be on my end, I've haven't run it for days, so must be an issue with being a "slim" client. How do I make it a full client, I can't seem to find an option anywhere as I can't rely on an unstable backend somewhere?

**Comment by almindor** [comment]
It seems `geth` is having issues. The one running on etherwall server has failed and the backup server at infura is now unavailable as well due to too many requests.

I've tried using a third infura server for the time being but I'm receiving errors from it which is odd. For the time being I'm afraid the server is down.

**Comment by almindor** [comment]
The main server's geth (local, unlimited) is now catching up from ~2 months ago and should be back up in a couple of hours.

**Comment by almindor** [comment]
The server's geth node is now back online and should be processing requests normally again.

**Comment by almindor** [comment]
Reopening this issue as the geth server keeps having problems. I'm pointing to an infura as backup but that one runs out of request quota quickly. I'm re-syncing the server geth from scratch now.

**Comment by almindor** [comment]
Server is back on tip, I've added `btrfs` snapshotting so I can recover the chaindata next time there's a corruption.
