### ISSUE TITLE
blockchain update etherwall 1.4.5

### ISSUE THREAD

**Issue by crazyearner** [almindor/etherwall#14]
Wallet is not updating and connecting to download and update wallet need advise on how to cure as connecting to 0 peers

**Comment by almindor** [comment]
Hey,

are you on ETH or ETC chain? I know that ETC has issues with seed nodes. It might also be caused by the current DDOS attack.

Syncing is purely a backend thing, Etherwall just uses `geth` to handle the blockchain.

Can you provide the last 10 or so lines from the Geth log? Open the log/geth tab and make a screenshot to attach here. (double check there's no personal information you might not want to disclose first!)

**Comment by crazyearner** [comment]
Have since deleted everything and started over seems to of cured problem
