### ISSUE TITLE
TLS Initialization Error after reinstalling Windows

### ISSUE THREAD

**Issue by captblotto** [almindor/etherwall#144]
I had to reinstall Windows 10 because of a stupid printer issue. I used the built in reset windows and kept my files. I also backed my Appdata folder to my NAS. Etherwall was on a completely separate drive from my OS C: drive.

Now when I open Etherwall I get the TLS Initialization error. 

HTTP Request error: TLS initialization failed
HTTP Request error: TLS initialization failed
Response parse error: illegal value
HTTP Request error: TLS initialization failed
HTTP Request error: TLS initialization failed
Connecting to main Etherwall server

**Comment by captblotto** [comment]
Its working now but my wallet is missing. Am I just screwed without the .etherwall backup file?

**Comment by almindor** [comment]
The server was down i had to issue a hw restart with the hosting provider.

What do you mean by wallet missing?

Dňa nedeľa, 8. januára 2023,  captblotto napísal:
> Its working now but my wallet is missing. Am I just screwed without the .etherwall backup file?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/almindor/etherwall/issues/144#issuecomment-1375065664
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by captblotto** [comment]
When I open Etherwall my address doesn't show up. It just says New Wallet

**Comment by captblotto** [comment]
I don't know if I have the wrong settings in Geth Data directory and or geth path? The FAQ says there is a keystore subfolder. 

I found that folder under C:/user/"name of user"/App Data/Local/Ethereum/keystore
but there's no files under that folder. I even found a copy of my entire C: drive from a few months ago and that folder is empty.

**Comment by almindor** [comment]
`C:/user/"name of user"/App Data/Local/Ethereum/keystore` should be correct. It's where geth (which Etherwall uses for account handling and encryption) stores the keys.

Did you do any backup from within etherwall prior to the reinstall? (e.g. wallet backup or individual account backup via right click menu)

Each account is contained in a file that looks like `UTC--2015-08-12T23-11-21.237620222Z--c64b50db57c0362e27a32b65bd29363f29fdfa59` where the date is creation time and the account address at the end. The files are JSON (you can look at them as text).

Your accounts should've been stored in the C drive since that's what geth uses by default (it's the datafolder location). If you want to use a different location you can specify it in the datafolder settings but you'd have to move or copy the folder from the original place.

Your backup of the C drive "should" have the files there. Maybe try also searching for files begining with `UTC--` on the disk as a whole (and the backup).

**Comment by captblotto** [comment]
Ok I found a file with UTC. Now I'm getting an error about unable to establish IPC Connection to geth. Fix path to geth and try again.

Is that the geth path? And if so should it be pointing to geth.exe? I have a geth.exe in the same folder as Etherwall.

**Comment by almindor** [comment]
> Ok I found a file with UTC. Now I'm getting an error about unable to establish IPC Connection to geth. Fix path to geth and try again.
> 
> Is that the geth path? And if so should it be pointing to geth.exe? I have a geth.exe in the same folder as Etherwall.

You need to copy the UTC files to the keystore subfolder under the datadir that is configured. As for geth path yes, it needs to point to a geth.exe file (it can be other than the one provided by etherwall but be careful where you get it from!)

**Comment by captblotto** [comment]
It's BACK! I don't know what was going on but it's working now. I have it restored. Thank you.
