### ISSUE TITLE
USDC Stuck. PLEASE HELP!

### ISSUE THREAD

**Issue by monkeyfart34** [almindor/etherwall#145]
I sent around $10 of USDC to my wallet address. looking on Etherscan.io, it has been transferred, how ever I can see/send it anywhere. **_PLEASE HELP_**

**Comment by almindor** [comment]
Did you add the USDC token to the list? Etherwall is a bit old schoold ERC20s don't get autodetected, you need to add the contract for each

**Comment by monkeyfart34** [comment]
> Did you add the USDC token to the list? Etherwall is a bit old schoold ERC20s don't get autodetected, you need to add the contract for each

I'm much more used to monero/btc. How would I do this?

**Comment by almindor** [comment]
See https://etherwall.com/faq/#tokens as for USDC you can find the address at https://etherscan.io (note that the actual current version ERC20 contract might not be the 1st you find).

You should be able to just "Add existing contract" in the contracts tab. Once added, USDC should be selectable in the list on the top right drop down for currencies and you should be able to send it out in the transactions (again by selecting the token in the dropdown there).

NOTE: even if something doesn't work, you can still get to your USDC using other methods, as long as you have access to your accoun/address you can use it with other wallets etc. The ERC20 support in Etherwall is rather shallow, when I implemented it most ERC20s were simple contracts. They since added "layers and proxy contracts" so they can do on blockchain contract upgrades resulting in de-facto "redirects". These contracts won't work with Etherwall.

If you do get trouble adding it, that might be the reason. In that case I suggest exporting you account and using it with some more token focused wallet.

**Comment by monkeyfart34** [comment]
> See https://etherwall.com/faq/#tokens as for USDC you can find the address at https://etherscan.io (note that the actual current version ERC20 contract might not be the 1st you find).
> 
> You should be able to just "Add existing contract" in the contracts tab. Once added, USDC should be selectable in the list on the top right drop down for currencies and you should be able to send it out in the transactions (again by selecting the token in the dropdown there).
> 
> NOTE: even if something doesn't work, you can still get to your USDC using other methods, as long as you have access to your accoun/address you can use it with other wallets etc. The ERC20 support in Etherwall is rather shallow, when I implemented it most ERC20s were simple contracts. They since added "layers and proxy contracts" so they can do on blockchain contract upgrades resulting in de-facto "redirects". These contracts won't work with Etherwall.
> 
> If you do get trouble adding it, that might be the reason. In that case I suggest exporting you account and using it with some more token focused wallet.

I've tried exporting it, It straight up doesn't write to a file, it doesn't export anything

**Comment by monkeyfart34** [comment]
> > See https://etherwall.com/faq/#tokens as for USDC you can find the address at https://etherscan.io (note that the actual current version ERC20 contract might not be the 1st you find).
> > You should be able to just "Add existing contract" in the contracts tab. Once added, USDC should be selectable in the list on the top right drop down for currencies and you should be able to send it out in the transactions (again by selecting the token in the dropdown there).
> > NOTE: even if something doesn't work, you can still get to your USDC using other methods, as long as you have access to your accoun/address you can use it with other wallets etc. The ERC20 support in Etherwall is rather shallow, when I implemented it most ERC20s were simple contracts. They since added "layers and proxy contracts" so they can do on blockchain contract upgrades resulting in de-facto "redirects". These contracts won't work with Etherwall.
> > If you do get trouble adding it, that might be the reason. In that case I suggest exporting you account and using it with some more token focused wallet.
> 
> I've tried exporting it, It straight up doesn't write to a file, it doesn't export anything

```
Wallet export error: Export account count mismatch, expected 2 exported 0
Wallet export error: Export account count mismatch, expected 2 exported 0
Wallet export error: Export account count mismatch, expected 2 exported 0
Wallet export error: Export account count mismatch, expected 2 exported 0

```

**Comment by almindor** [comment]
Hmm, I will have to look into that as a bug. In the meantime Etherwall keeps all your account in the "datadir" folder from settings tab, under the keystore subfolder.

Each file there is a JSON containing the account information, encrypted with your password and is compatible to pretty much any other wallet out there.

**Comment by almindor** [comment]
Also forgot to ask, what OS/version is this on? I just tried export and it worked fine for me.

**Comment by monkeyfart34** [comment]
This is on windows 10. I don't have access to the original files anymore. i moved the folder to a different spot as they were on a usb originaly
