### ISSUE TITLE
deposit to etherwall desktop wallet did not reach it

### ISSUE THREAD

**Issue by mzuther86** [almindor/etherwall#22]
hi there,

i´m new here and want to thank all of you in advance for your help. i just downloaded etherwall desktop wallet a couple days ago and as a newbie directly tried to deposit ether on it. then i realised that it has to download the history of the bloxckchain to the actual version, i did not worry to much and waited till this was finished and thought then my ether will appear as funds, but this did not happen. in the blockexplorer the transaction is shown as executed. how can i reach my ether now, what should i do?

best regards

Michael

**Comment by almindor** [comment]
Hello Michael.

In order to help I need to understand your situation a bit better.

Where did you send the ether from? Was it another wallet or exchange?
If your transaction is on an explorer and your account also shows said balance your ETH are probably ok as long as you didn't make a mistake in the address.

Which version of etherwall are you running? I know you said you downloaded a couple of days ago but version 2.0.0 was recently released so I'm trying to find out if you just missed it (especially since version 2 doesn't require a full sync anymore unless you want to).

Is it possible to send me the address you sent to? If you want to keep it private you can send it to me on email almindor {at} gmail {dot} com

**Comment by mzuther86** [comment]
hi almindor,

thanks for your reply. i wanted to change the tokens from btc via shapeshift, i sent from a btc desktop wallet (electrum), here is the blockchain report that says its sent to my etherwall wallet adress:

https://etherscan.io/address/0x671060a5648d1CB7Db67403Bd61827f6491965c7

the adress is correct, i still have the old version and will update now

**Comment by mzuther86** [comment]
with the new version it shows the payment, thanks alot.

**Comment by almindor** [comment]
Hey, so your geth client wasn't fully synced yet. With 2.0.0 you're always up to speed right away tho :) Glad it worked.
