### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Wienerin** [almindor/etherwall#27]
Hello

I have an error in the last number
 
Wrong address: 0xaFB6a92ee4d8818C745297d0F5BE1D3872F19510
 
Correct address: 0xAFb6a92EE4D8818c745297d0f5Be1D3872f1951f
 
not 9510 rather 951f
 
Best Regard
Wienerin

**Comment by almindor** [comment]
Hello,

sorry for the long delay but I've been abroad until recently and without any internet connection.

I need some more information to understand your problem.

1. What's your OS version?
2. What is the Etherwall and Geth version?
3. What type of address is this (TREZOR/hd or normal) and how was it created?
4. How do you know it's supposed to end with `f` instead of `0` ?
5. Is this a new problem, when did this discrepancy appeared first?

Thanks, and sorry again for the long delay.

**Comment by almindor** [comment]
I looked up both addresses and their transactions on Etherscan.io to get a better understanding.

From what I can say you sent two subsequent transactions from `0x191F78Ef39341Ff46013059D4EEDC04365cAE588` first to `0xaFB6a92ee4d8818C745297d0F5BE1D3872F19510` and second to `0xAFb6a92EE4D8818c745297d0f5Be1D3872f1951f`.

So you sent to the wrong address initially and then corrected it with another send of same amount.

Was this a typo? Did you write the 0 at the end by accident, perhaps with a bad copy & paste?
Which version of Etherwall was this?

Version `2.0.1` was released just around the time of your transaction and it [re]added the [EIP55](https://github.com/ethereum/EIPs/issues/55) support for address "checksums".

If you just pasted the last character wrong you should've seen a warning about a checksum in the summary text, but only if you're on version `2.0.1`.

I'm afraid there is nothing I can do to revert the transaction however.

I have created issue #29 however as this is a serious UX problem that needs solving. I'll keep this issue open until you reply in case I didn't understand your problem correctly and there's something else to it than a bad copy & paste or a mistyping.

**Comment by Wienerin** [comment]
Etherwall Version 1.5

So you sent to the wrong address initially and then corrected it with another send of same amount.

Was this a typo? Did you write the 0 at the end by accident, perhaps with a bad copy & paste?
Which version of Etherwall was this?

Yes I have copy & paste.

Please let me know the eth? to this address: 0x191F78Ef39341Ff46013059D4EEDC04365cAE588

Best regards 

Wienerin

**Comment by Wienerin** [comment]
I have Windows 7

**Comment by almindor** [comment]
I'm afraid it's not possible for me to do anything with the 10 ether in the wrong address.
If you send ether to the wrong address it's irrevocably lost, same as if you burned money because nobody has the private key to that address.

I'm really sorry but there's nothing that can be done aside from making more strict checks via #29

**Comment by Wienerin** [comment]
According to Etherscan Team you can send me the money back ..

Hi Julia Wienerin,

A transaction in the Ethereum blockchain is irreversible. 

As a free Blockexplorer service we can only provide and display information on transactions that occurs on the Ethereum Blockchain. We are unable to troubleshoot transaction failures. For issues related to your Wallet, please contact your wallet provider directly as they are in a better position to assist you. And at no time do we have control or access to your funds or private keys as we do not provide wallet services.

Thank you.

Regards
-  Etherscan Team

**Comment by almindor** [comment]
They didn't say I can they just said that they cannot, which is true.

You must understand that each address is bound to a private key and you can only send from an address if you have the private key for it.

By mistyping or mis-pasting you sent your ETH to an address that nobody has private key to. I cannot do anything with that ether, nobody can.

If I mistyped my send I'd lose the ETH as well. I'm really sorry but there really is nothing anyone can do about it.
