### ISSUE TITLE
2.0.1 Thin Client doesn't work

### ISSUE THREAD

**Issue by pwdrhash** [almindor/etherwall#30]
Upon startup I get "Starting Geth" in the main window and then an Error popup that says "WS: Disconnected from websocket".
Here is the log:

WS: Disconnected from websocket
WS: QLocalSocket::connectToServer: Invalid name
WS: QLocalSocket::connectToServer: Invalid name
Geth starting /usr/local/Cellar/ethereum/1.6.6/bin --syncmode=fast --cache 512 --datadir /Users/joeblow/Library/Ethereum --maxpeers=0 --nodiscover --nat=none
Checking to see if there is an already running geth...
Etherwall starting

I have not been able to get 2.0.1 to work. I'm running OS X 10.12.5.

**Comment by almindor** [comment]
Hmm the `invalid name` in the WS error is odd. It works for me on my mac os x (mac book pro), correct block and everything, server is fine too.

I'm also running 10.12.5 so that's not the issue.

If you turn off thin client and let geth sync does it synchronize? No need to wait for a full sync I just want to see if it's connections work ok.

The only thing I can think of is there's some problem connecting from your network for some reason. The server is hosted on linode so it should be fully accessible.

Can you also try doing `traceroute api2.etherwall.com` and paste the output here?

**Comment by almindor** [comment]
I'm going to close this issue as there was no reply from the creator.
