### ISSUE TITLE
etherwall to bittrex

### ISSUE THREAD

**Issue by wujomasta** [almindor/etherwall#46]
Hello,

1st of all sorry to confuse by previous replys etc.

Could you please help me with following issue
I tried to trnasfer some ETH into bittrex platform, 
I did generate code on bittrex but had an error on etherwall, please take look on screetshots

i did contact bittrex support as well but it take longer for them to respond

![bittrex](https://user-images.githubusercontent.com/30832376/29265256-4aff7b3e-80d8-11e7-9843-0367d2020615.jpg)
![etherwall](https://user-images.githubusercontent.com/30832376/29265257-4b092ee0-80d8-11e7-8507-6bbc2fbab98c.jpg)

**Comment by almindor** [comment]
OK so this means that bittrex didn't implement [EIP 55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) yet.

EIP55 is meant to prevent errors in address copy& paste or typing by doing a "checksum". Since Ethereum didn't introduce a checksum mechanism from start, Vitalik created this method. It uses capitalisation to check if the address is correct.

In your case it's safe to send, however Bittrex should capitalize their addresses properly and implement EIP 55.

If you take your address from bitrex and paste it into [Etherscan.io](https://etherscan.io) you will see an info page and the address will be properly capitalized there. You can then put that in Etherwall and the warning should go away.

I'd ask Bittrex to implement EIP 55 tho, this makes them look incompetent. If one guy can do it so can they.
