### ISSUE TITLE
No events in Thin client mode

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#70]
When I switch to Thin client, there are the contracts and watches, but no events which I get in full node mode.

**Comment by almindor** [comment]
Hey, events are not loaded from "history" in thin client. This is because the log size is quite considerable in some cases.

You should still get "new" events as they come in, but you won't get any previous events populated when you add a watch/restart etherwall.

This is by design to ensure the remote node (which is shared) is not overloaded.
