### ISSUE TITLE
Exporting private key

### ISSUE THREAD

**Issue by Tuen** [almindor/etherwall#78]
Is there a way I can export the private key so that I can import it into a different wallet?

**Comment by almindor** [comment]
Hey, which wallet do you need to import into?

Neither Etherwall nor Geth currently allow "decrypting" of the private key. You should be able to export the account encrypted (as a JSON file) by right clicking and exporting to directory. NOTE: this is saved in the geth compatible format that stays encrypted with your password.

The reason Etherwall doesn't allow getting the raw private key is simply because Geth doesn't expose that functionality and Etherwall uses geth for account security.

If you really need to get the raw private key export the geth account and import it into MyEtherWallet. I believe they have the option of getting the raw key out.

NOTE: ensure you check the URL/source of any webpage/software you use and double-check the SSL certificates too.

**Comment by Tuen** [comment]
Thanks for the advice almindor. Really appreciate it.
I exported the wallet backup file and imported it into MetaMask. But I received this error:

![image](https://user-images.githubusercontent.com/34783044/34323334-f38ae70c-e898-11e7-9ba1-9d8b51c09c99.png)

Is this because Metamask is not compatible with the json export from Etherwall? What does the error "unexpected token in JSON at position 0" mean?

Would I get the same error with MyEtherWallet?

Any advice much appreciated!

Thanks!

**Comment by almindor** [comment]
I think you mixed up the two export types.

There's a "wallet/export" in main menu which is Etherwall-only and exports the whole wallet with all accounts and settings. This is not compatible with anything outside Etherwall.

What you want for Metamask and others is go to accounts tab, select your desired account and right click and select export account to directory.

NOTE: the filename will be something like UTC--<address>--<timestamp>

![export_single_account](https://user-images.githubusercontent.com/1950958/34323434-ec538ee6-e805-11e7-8d3c-09403d8c0a86.png)

**Comment by Tuen** [comment]
Oh wow! Thanks so much for that. I didn't realise there was another export function. I'll try that out!

**Comment by Tuen** [comment]
It worked! Thanks a lot for the help.

**Comment by almindor** [comment]
Glad to hear it, closing issue
