### ISSUE TITLE
Contract address invalid checksum

### ISSUE THREAD

**Issue by AJGierer** [almindor/etherwall#84]
I'm getting a "Contract address invalid checksum" when trying to Add Existing Contract for the SERENITY Token ICO.
Any thoughts how to fix this?

**Comment by almindor** [comment]
See [the FAQ entry on checksums](https://www.etherwall.com/faq/#checksum)

Your address source is probably low quality. If the whole address is lowercase then paste it into etherscan, double check it and get the capitalized version from there.

**Comment by AJGierer** [comment]
Thank you. I see it in the FAQ now, smh.

I was able to add the contract but now I'm catching a "gas required exceeds allowance or always failing transaction" error.
Not sure it matters as it looks like the balance was transferred to my account anyway. Wanted to just give the heads up in case something is wrong, however.

Thanks again!

**Comment by almindor** [comment]
Hmm so the error you got happens when estimate is called and the contract function would throw an error for example.

This can happen with tokens if you're for example using an account that has no tokens of said type. Etherwall tries to estimate the gas and it comes back as an error because the contract would actually throw (not enough funds).

It shouldn't have happened if your account had funds tho and they went out ok. I'll close this issue as it's unrelated but if you keep getting the gas error on transaction setups that should work please open a separate issue with screenshots if possible.

Thanks
