### ISSUE TITLE
Wrong balance with ropsten network

### ISSUE THREAD

**Issue by lockie** [almindor/etherwall#89]
Hello.
I have a problem with account balance using ropsten network. Here's what I've done:
1. set additional Geth args to`--syncmode=fast --cache 512 --testnet`
2. turned off thin client
3. Got 1 ether from faucet, here it is: https://ropsten.etherscan.io/address/0x09FE965D59ef7cB566B3bEDF8239fcDcae9ef53A
4. Waited for Geth to sync 2.8M blocks out of ropsten.

Still, the account balance in Etherwall is zero: https://imgur.com/a/sggYE
I'm using Etherwall 2.2.1 and Geth 1.8.2.
Thanks in advance.

**Comment by almindor** [comment]
Hmm I didn't use ropsten for a while because it had issues. This is probably a geth problem tho. Can you do `geth attach` in another terminal and see what `eth.getBalance(eth.accounts[0]);` gives you?

NOTE: change the `[0]` in that command to whatever index for that account in the `eth.accounts` list. You can also use `"0x0000..."` direct address instead in the `eth.getBalance()` call.

If you get a 0 there too it's a geth issue, you might be on the wrong fork which did use to happen on ropsten (that's why EW uses rinkeby by default now).

**Comment by lockie** [comment]
> Can you do geth attach in another terminal and see what eth.getBalance(eth.accounts[0]); gives you?

Yeah, it gives zero. I suppose I should report it under go-ethereum then?

**Comment by almindor** [comment]
Correct. Chances are it's just a fork/split and you're on some bad ropsten chain. Try re-syncing from scratch.

**Comment by lockie** [comment]
All right, thanks for your help!
